################################################################################
# Terraform Outputs - vote3 Infrastructure
# Generated by Opsera Code-to-Cloud Enterprise v0.905
################################################################################

# ECR Repositories
output "ecr_vote_repository_url" {
  description = "ECR repository URL for vote service"
  value       = aws_ecr_repository.vote.repository_url
}

output "ecr_result_repository_url" {
  description = "ECR repository URL for result service"
  value       = aws_ecr_repository.result.repository_url
}

output "ecr_worker_repository_url" {
  description = "ECR repository URL for worker service"
  value       = aws_ecr_repository.worker.repository_url
}

# Database Endpoints
output "rds_endpoint" {
  description = "RDS PostgreSQL endpoint"
  value       = aws_db_instance.postgres.endpoint
}

output "rds_address" {
  description = "RDS PostgreSQL address (host only)"
  value       = aws_db_instance.postgres.address
}

output "elasticache_endpoint" {
  description = "ElastiCache Redis endpoint"
  value       = aws_elasticache_cluster.redis.cache_nodes[0].address
}

# IRSA Role ARNs
output "irsa_vote_role_arn" {
  description = "IRSA role ARN for vote service"
  value       = aws_iam_role.vote.arn
}

output "irsa_result_role_arn" {
  description = "IRSA role ARN for result service"
  value       = aws_iam_role.result.arn
}

output "irsa_worker_role_arn" {
  description = "IRSA role ARN for worker service"
  value       = aws_iam_role.worker.arn
}
