# QA Environment Variables
# Generated by Opsera Code-to-Cloud Enterprise v0.905

app_name    = "vote3"
environment = "qa"
tenant      = "opsera"
aws_region  = "us-west-2"

# RDS - Small for QA
rds_instance_class    = "db.t3.micro"
rds_allocated_storage = 20

# ElastiCache - Small for QA
elasticache_node_type       = "cache.t3.micro"
elasticache_num_cache_nodes = 1
