# Staging Environment Variables
# Generated by Opsera Code-to-Cloud Enterprise v0.905

app_name    = "vote3"
environment = "staging"
tenant      = "opsera"
aws_region  = "us-west-2"

# RDS - Medium for staging
rds_instance_class    = "db.t3.small"
rds_allocated_storage = 50

# ElastiCache - Medium for staging
elasticache_node_type       = "cache.t3.small"
elasticache_num_cache_nodes = 1
