name: "99-Pod Logs (sperivote11)"

on:
  workflow_dispatch:

env:
  APP_NAME: sperivote11
  ENVIRONMENT: dev
  AWS_REGION: us-west-2
  SPOKE_CLUSTER: opsera-usw2-np

jobs:
  logs:
    name: "📋 Pod Logs"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        run: aws eks update-kubeconfig --name ${{ env.SPOKE_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Get Pod Status
        run: |
          echo "### Pod Status" >> $GITHUB_STEP_SUMMARY
          kubectl get pods -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} -o wide
          echo '```' >> $GITHUB_STEP_SUMMARY
          kubectl get pods -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Worker Logs
        run: |
          echo "=== WORKER LOGS ==="
          kubectl logs -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} -l app=worker --tail=100 || echo "No logs"

      - name: Result Logs
        run: |
          echo "=== RESULT LOGS ==="
          kubectl logs -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} -l app=result --tail=50 || echo "No logs"

      - name: Worker Env Check
        run: |
          echo "=== WORKER ENV ==="
          kubectl exec -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} deploy/worker -- env | grep -E "(DATABASE|AWS|REDIS)" || echo "Could not get env"

      - name: Fix RDS Connection Pool
        run: |
          echo "Scaling down result to clear RDS connections..."
          kubectl scale deployment/result -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} --replicas=0
          kubectl scale deployment/worker -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} --replicas=0
          echo "Waiting 30s for connections to clear..."
          sleep 30
          echo "Scaling back up..."
          kubectl scale deployment/worker -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} --replicas=1
          sleep 5
          kubectl scale deployment/result -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} --replicas=1
          kubectl rollout status deployment/result -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} --timeout=90s
          kubectl rollout status deployment/worker -n ${{ env.APP_NAME }}-${{ env.ENVIRONMENT }} --timeout=90s
