FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /source
COPY worker/*.csproj ./
RUN dotnet restore
COPY worker/ ./
RUN dotnet publish -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app
COPY --from=build /app .
ENV DOTNET_EnableDiagnostics=0
ENTRYPOINT ["dotnet", "Worker.dll"]
