################################################################################
# Terraform Configuration - sperivote11 Infrastructure
# Generated by Opsera Code-to-Cloud Enterprise v0.905
################################################################################

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }

  backend "s3" {
    bucket         = "opsera-terraform-state-usw2"
    key            = "sperivote11/dev/terraform.tfstate"
    region         = "us-west-2"
    encrypt        = true
    dynamodb_table = "terraform-locks"
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Application = var.app_name
      Environment = var.environment
      Tenant      = var.tenant
      ManagedBy   = "Terraform"
      Skill       = "code-to-cloud-enterprise-v0.905"
    }
  }
}

locals {
  name_prefix = "${var.app_name}-${var.environment}"
  namespace   = "${var.app_name}-${var.environment}"
}

################################################################################
# Data Sources - Existing Infrastructure
################################################################################

data "aws_caller_identity" "current" {}

data "aws_eks_cluster" "existing" {
  name = "${var.tenant}-usw2-np"
}

data "aws_vpc" "existing" {
  id = data.aws_eks_cluster.existing.vpc_config[0].vpc_id
}

data "aws_subnets" "private" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.existing.id]
  }
  filter {
    name   = "tag:Name"
    values = ["*private*"]
  }
}

################################################################################
# ECR Repositories
################################################################################

resource "aws_ecr_repository" "vote" {
  name                 = "${local.name_prefix}-vote"
  image_tag_mutability = "MUTABLE"
  image_scanning_configuration { scan_on_push = true }
  encryption_configuration { encryption_type = "AES256" }
}

resource "aws_ecr_repository" "result" {
  name                 = "${local.name_prefix}-result"
  image_tag_mutability = "MUTABLE"
  image_scanning_configuration { scan_on_push = true }
  encryption_configuration { encryption_type = "AES256" }
}

resource "aws_ecr_repository" "worker" {
  name                 = "${local.name_prefix}-worker"
  image_tag_mutability = "MUTABLE"
  image_scanning_configuration { scan_on_push = true }
  encryption_configuration { encryption_type = "AES256" }
}

# ECR Lifecycle Policies - Keep last 10 images
resource "aws_ecr_lifecycle_policy" "vote" {
  repository = aws_ecr_repository.vote.name
  policy = jsonencode({
    rules = [{ rulePriority = 1, description = "Keep last 10", selection = { tagStatus = "any", countType = "imageCountMoreThan", countNumber = 10 }, action = { type = "expire" } }]
  })
}

resource "aws_ecr_lifecycle_policy" "result" {
  repository = aws_ecr_repository.result.name
  policy = jsonencode({
    rules = [{ rulePriority = 1, description = "Keep last 10", selection = { tagStatus = "any", countType = "imageCountMoreThan", countNumber = 10 }, action = { type = "expire" } }]
  })
}

resource "aws_ecr_lifecycle_policy" "worker" {
  repository = aws_ecr_repository.worker.name
  policy = jsonencode({
    rules = [{ rulePriority = 1, description = "Keep last 10", selection = { tagStatus = "any", countType = "imageCountMoreThan", countNumber = 10 }, action = { type = "expire" } }]
  })
}

################################################################################
# Security Groups
################################################################################

resource "aws_security_group" "rds" {
  name        = "${local.name_prefix}-rds-sg"
  description = "RDS PostgreSQL security group"
  vpc_id      = data.aws_vpc.existing.id

  ingress {
    description = "PostgreSQL from VPC"
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = [data.aws_vpc.existing.cidr_block]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "elasticache" {
  name        = "${local.name_prefix}-elasticache-sg"
  description = "ElastiCache Redis security group"
  vpc_id      = data.aws_vpc.existing.id

  ingress {
    description = "Redis from VPC"
    from_port   = 6379
    to_port     = 6379
    protocol    = "tcp"
    cidr_blocks = [data.aws_vpc.existing.cidr_block]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

################################################################################
# RDS PostgreSQL
################################################################################

resource "aws_db_subnet_group" "main" {
  name       = "${local.name_prefix}-db-subnet-group"
  subnet_ids = data.aws_subnets.private.ids
}

resource "random_password" "rds_master" {
  length  = 32
  special = false  # RDS has limited special char support
}

resource "aws_secretsmanager_secret" "rds_master" {
  name                    = "${local.name_prefix}-rds-master"
  recovery_window_in_days = 0  # Allow immediate deletion for dev
}

resource "aws_secretsmanager_secret_version" "rds_master" {
  secret_id = aws_secretsmanager_secret.rds_master.id
  secret_string = jsonencode({
    username = "postgres_admin"
    password = random_password.rds_master.result
    host     = aws_db_instance.postgres.address
    database = "votes"
  })
}

resource "aws_db_instance" "postgres" {
  identifier     = "${local.name_prefix}-postgres"
  engine         = "postgres"
  engine_version = "16.6"
  instance_class = var.rds_instance_class
  allocated_storage = var.rds_allocated_storage
  storage_type   = "gp3"

  db_name  = "votes"
  username = "postgres_admin"
  password = random_password.rds_master.result

  iam_database_authentication_enabled = true
  vpc_security_group_ids = [aws_security_group.rds.id]
  db_subnet_group_name   = aws_db_subnet_group.main.name

  multi_az            = false
  publicly_accessible = false
  skip_final_snapshot = true

  backup_retention_period = 7
  backup_window          = "03:00-04:00"
  maintenance_window     = "Mon:04:00-Mon:05:00"

  performance_insights_enabled = true
  monitoring_interval         = 60
  monitoring_role_arn         = aws_iam_role.rds_monitoring.arn
}

resource "aws_iam_role" "rds_monitoring" {
  name = "${local.name_prefix}-rds-monitoring"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "monitoring.rds.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "rds_monitoring" {
  role       = aws_iam_role.rds_monitoring.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

################################################################################
# ElastiCache Redis
################################################################################

resource "aws_elasticache_subnet_group" "main" {
  name       = "${local.name_prefix}-cache-subnet"
  subnet_ids = data.aws_subnets.private.ids
}

resource "aws_elasticache_cluster" "redis" {
  cluster_id           = "${local.name_prefix}-redis"
  engine               = "redis"
  engine_version       = "7.0"
  node_type            = var.elasticache_node_type
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  port                 = 6379
  subnet_group_name    = aws_elasticache_subnet_group.main.name
  security_group_ids   = [aws_security_group.elasticache.id]
}

################################################################################
# IRSA - IAM Roles for Service Accounts
################################################################################

data "aws_iam_openid_connect_provider" "eks" {
  url = data.aws_eks_cluster.existing.identity[0].oidc[0].issuer
}

locals {
  oidc_provider_arn = data.aws_iam_openid_connect_provider.eks.arn
  oidc_provider_url = replace(data.aws_eks_cluster.existing.identity[0].oidc[0].issuer, "https://", "")
}

resource "aws_iam_role" "vote" {
  name = "${local.name_prefix}-vote-irsa"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Federated = local.oidc_provider_arn }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = { StringEquals = { "${local.oidc_provider_url}:aud" = "sts.amazonaws.com", "${local.oidc_provider_url}:sub" = "system:serviceaccount:${local.namespace}:vote" } }
    }]
  })
}

resource "aws_iam_role" "result" {
  name = "${local.name_prefix}-result-irsa"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Federated = local.oidc_provider_arn }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = { StringEquals = { "${local.oidc_provider_url}:aud" = "sts.amazonaws.com", "${local.oidc_provider_url}:sub" = "system:serviceaccount:${local.namespace}:result" } }
    }]
  })
}

resource "aws_iam_role" "worker" {
  name = "${local.name_prefix}-worker-irsa"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Federated = local.oidc_provider_arn }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = { StringEquals = { "${local.oidc_provider_url}:aud" = "sts.amazonaws.com", "${local.oidc_provider_url}:sub" = "system:serviceaccount:${local.namespace}:worker" } }
    }]
  })
}

# Secrets Manager read policy for apps to get RDS credentials
resource "aws_iam_policy" "secrets_read" {
  name = "${local.name_prefix}-secrets-read"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["secretsmanager:GetSecretValue"]
      Resource = [aws_secretsmanager_secret.rds_master.arn]
    }]
  })
}

# Attach Secrets Manager read policy to worker and result (for password auth)
resource "aws_iam_role_policy_attachment" "result_secrets" {
  role       = aws_iam_role.result.name
  policy_arn = aws_iam_policy.secrets_read.arn
}

resource "aws_iam_role_policy_attachment" "worker_secrets" {
  role       = aws_iam_role.worker.name
  policy_arn = aws_iam_policy.secrets_read.arn
}
